# Site
name: "Cbp Tech Blog"
title: "Cbp Tech Blog"
description: "Blog technique de Cbp."
logo: 'assets/images/favicon.ico'
favicon: 'assets/images/favicon.ico'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  seb:
    name: Seb
    display_name: "Sebastien Errien"
    avatar: 'assets/images/seb.jpg'
    email: sebastien.errien@cbp-group.com
    twitter: https://twitter.com/SebErrien
    description: "Tall | Computer scientist | Amateur guitarist | Cbp Platforms Architect and Product Owner."
  gde:
    name: Guillaume
    display_name: "Guillaume Deleplace"
    avatar: 'assets/images/gde.jpg'
    email: guillaume.deleplace@cbp-group.com
    twitter: https://twitter.com/gdeleplace
    description: "Scrum Master chez Cbp - Coach Professionnel"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true


# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [LICENSE.txt, README.md, Gemfile, Gemfile.lock]
